# Generated by Django 3.0.14 on 2023-08-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=40)),
                ('available_quantity', models.FloatField()),
                ('measurement_unit', models.CharField(max_length=40)),
                ('price_per_unit', models.FloatField()),
            ],
            options={
                'ordering': ['ingredient'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=40)),
                ('ingredient_quantity', models.FloatField()),
                ('measurement_unit', models.CharField(max_length=40)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Ingredient')),
            ],
            options={
                'ordering': ['menu_item'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.RecipeRequirements')),
            ],
            options={
                'ordering': ['menu_item'],
            },
        ),
    ]
