# Generated by Django 3.0.14 on 2023-08-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230809_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['timestamp']},
        ),
    ]
