# Generated by Django 3.0.14 on 2023-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20230809_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirements',
            name='menu_item',
            field=models.CharField(max_length=40),
        ),
    ]
